// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elvxjxjrrbbfiephzswv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsdnhqeGpycmJiZmllcGh6c3d2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwOTY1OTcsImV4cCI6MjA1ODY3MjU5N30.Gi4Mx_211rHfIz1Nt_swA9qVusc-AWsyGDNgVZr7Z9o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);